import React, { useState } from 'react';
import { 
  Download, 
  FileText, 
  Bookmark, 
  Check, 
  X, 
  Music, 
  Share2, 
  Sparkles, 
  Upload, 
  Sliders, 
  Layers, 
  Clock 
} from 'lucide-react';
import { TrackDef, TransitionConfig } from '../types';

interface SetExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  tracks: TrackDef[];
  transitions: TransitionConfig[];
  onSaveAsPlaylist: (name: string) => void;
  onImportProject?: (tracks: TrackDef[], transitions: TransitionConfig[]) => void;
}

export default function SetExportModal({
  isOpen,
  onClose,
  tracks,
  transitions,
  onSaveAsPlaylist,
  onImportProject,
}: SetExportModalProps) {
  const [playlistName, setPlaylistName] = useState(
    () => `Techno Set - ${new Date().toLocaleDateString('de-DE')}`
  );
  const [isSavedPlaylist, setIsSavedPlaylist] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState<string | null>(null);

  if (!isOpen) return null;

  const totalDurationSec = tracks.reduce((acc, t) => acc + (t.duration || 180), 0);

  const formatTime = (totalSeconds: number) => {
    const mins = Math.floor(totalSeconds / 60);
    const secs = Math.floor(totalSeconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  // 1. Save Set as Playlist in Left Sidebar
  const handleSavePlaylist = () => {
    if (!playlistName.trim()) return;
    onSaveAsPlaylist(playlistName.trim());
    setIsSavedPlaylist(true);
    setTimeout(() => setIsSavedPlaylist(false), 3000);
  };

  // 2. Export M3U8 Playlist
  const handleExportM3U = () => {
    if (tracks.length === 0) return;
    let content = '#EXTM3U\n';
    tracks.forEach((t) => {
      const dur = Math.round(t.duration || 0);
      content += `#EXTINF:${dur},${t.artist} - ${t.title}\n`;
      content += `${t.filePath || t.filename || `${t.title}.mp3`}\n`;
    });

    const blob = new Blob([content], { type: 'audio/x-mpegurl;charset=utf-8' });
    downloadBlob(blob, `${playlistName.replace(/[^a-z0-9]/gi, '_')}.m3u8`);
    triggerSuccessFeedback('m3u');
  };

  // 3. Export CUE Sheet with calculated track start times
  const handleExportCue = () => {
    if (tracks.length === 0) return;

    let content = `REM Generated by MuLiMa Pro DJ Studio\n`;
    content += `PERFORMER "MuLiMa Pro DJ"\n`;
    content += `TITLE "${playlistName}"\n`;
    content += `FILE "DJ_Set.mp3" MP3\n`;

    let currentStartSec = 0;

    tracks.forEach((track, idx) => {
      const trackNum = (idx + 1).toString().padStart(2, '0');
      const startMin = Math.floor(currentStartSec / 60).toString().padStart(2, '0');
      const startSec = Math.floor(currentStartSec % 60).toString().padStart(2, '0');
      const startFrames = Math.floor((currentStartSec % 1) * 75).toString().padStart(2, '0');

      content += `  TRACK ${trackNum} AUDIO\n`;
      content += `    TITLE "${track.title}"\n`;
      content += `    PERFORMER "${track.artist}"\n`;
      content += `    INDEX 01 ${startMin}:${startSec}:${startFrames}\n`;

      // Advance time for next track based on transition duration
      const duration = track.duration || 180;
      if (idx < tracks.length - 1) {
        const nextTrack = tracks[idx + 1];
        const trans = transitions.find(
          t => t.sourceTrackId === track.id && t.targetTrackId === nextTrack.id
        ) || transitions.find(t => t.sourceTrackId === track.id);
        const bpm = track.bpm || 130;
        const beats = trans ? trans.durationBeats : 32;
        const transSec = beats * (60 / bpm);
        currentStartSec += Math.max(0, duration - transSec);
      } else {
        currentStartSec += duration;
      }
    });

    const blob = new Blob([content], { type: 'application/x-cue;charset=utf-8' });
    downloadBlob(blob, `${playlistName.replace(/[^a-z0-9]/gi, '_')}.cue`);
    triggerSuccessFeedback('cue');
  };

  // 4. Export JSON Project
  const handleExportJson = () => {
    const project = {
      name: playlistName,
      createdAt: new Date().toISOString(),
      generator: 'MuLiMa Pro DJ Studio',
      tracks,
      transitions,
    };
    const jsonStr = JSON.stringify(project, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    downloadBlob(blob, `${playlistName.replace(/[^a-z0-9]/gi, '_')}.mulimaset.json`);
    triggerSuccessFeedback('json');
  };

  // 5. Import JSON Project
  const handleFileImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const data = JSON.parse(event.target?.result as string);
        if (data.tracks && Array.isArray(data.tracks)) {
          onImportProject?.(data.tracks, data.transitions || []);
          if (data.name) setPlaylistName(data.name);
          onClose();
        }
      } catch (err) {
        console.error('Fehler beim Importieren des Set-Projekts:', err);
      }
    };
    reader.readAsText(file);
  };

  const downloadBlob = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const triggerSuccessFeedback = (type: string) => {
    setDownloadSuccess(type);
    setTimeout(() => setDownloadSuccess(null), 3000);
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-md p-4 select-none animate-fadeIn">
      <div className="bg-[#12141A] border border-[#242936] rounded-2xl w-full max-w-xl shadow-2xl overflow-hidden flex flex-col">
        
        {/* MODAL HEADER */}
        <div className="flex items-center justify-between p-5 border-b border-[#242936] bg-[#161920]">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-purple-600/20 border border-purple-500/30 text-purple-400">
              <Download className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white flex items-center gap-2">
                <span>DJ Set Export & Playliste Speichern</span>
              </h3>
              <p className="text-xs text-gray-400 font-mono">
                {tracks.length} Tracks • {transitions.length} Übergänge • Ca. {formatTime(totalDurationSec)} Gesamtlaufzeit
              </p>
            </div>
          </div>

          <button 
            onClick={onClose}
            className="p-1.5 rounded-lg text-gray-400 hover:text-white hover:bg-[#242936] transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* MODAL BODY */}
        <div className="p-6 flex flex-col gap-6 max-h-[75vh] overflow-y-auto">
          
          {/* 1. SAVE IN APP AS PLAYLIST */}
          <div className="bg-[#161920]/80 border border-[#242936] rounded-xl p-4 flex flex-col gap-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-sm font-bold text-white">
                <Bookmark className="w-4 h-4 text-purple-400" />
                <span>Als Playliste in MuLiMa Pro speichern</span>
              </div>
              <span className="text-[10px] font-mono text-gray-400 bg-[#0D0E12] px-2 py-0.5 rounded border border-[#242936]">
                Erscheint in linker Seitenleiste
              </span>
            </div>

            <div className="flex items-center gap-2">
              <input
                type="text"
                value={playlistName}
                onChange={(e) => setPlaylistName(e.target.value)}
                placeholder="Name des DJ Sets..."
                className="flex-1 bg-[#0D0E12] border border-[#242936] rounded-xl px-3 py-2 text-xs text-white focus:border-purple-500 outline-none font-mono"
              />
              <button
                onClick={handleSavePlaylist}
                className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-mono font-bold transition-all shadow-md ${
                  isSavedPlaylist
                    ? 'bg-emerald-600 text-white'
                    : 'bg-purple-600 hover:bg-purple-500 text-white active:scale-95'
                }`}
              >
                {isSavedPlaylist ? <Check className="w-3.5 h-3.5" /> : <Bookmark className="w-3.5 h-3.5" />}
                <span>{isSavedPlaylist ? 'Gespeichert!' : 'Speichern'}</span>
              </button>
            </div>
          </div>

          {/* 2. EXPORT OPTIONS GRID */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            
            {/* CUE Sheet Export */}
            <button
              onClick={handleExportCue}
              className="group flex flex-col items-start p-4 rounded-xl border border-[#242936] bg-[#161920]/60 hover:bg-[#1A1D26] hover:border-cyan-500/50 transition-all text-left shadow-lg relative overflow-hidden"
            >
              <div className="p-2 rounded-lg bg-cyan-500/10 text-cyan-400 border border-cyan-500/30 mb-2.5 group-hover:scale-110 transition-transform">
                <FileText className="w-4 h-4" />
              </div>
              <span className="text-xs font-bold text-white mb-0.5">CUE-Sheet (.cue)</span>
              <span className="text-[10px] text-gray-400 leading-relaxed">
                Track-Marker mit genauen Zeiten für Traktor, Rekordbox & CDJs.
              </span>
              {downloadSuccess === 'cue' && (
                <span className="absolute top-2 right-2 flex items-center gap-1 text-[9px] font-mono text-emerald-400 bg-emerald-950/80 px-2 py-0.5 rounded border border-emerald-500/40">
                  <Check className="w-3 h-3" /> Geladen
                </span>
              )}
            </button>

            {/* M3U8 Playlist Export */}
            <button
              onClick={handleExportM3U}
              className="group flex flex-col items-start p-4 rounded-xl border border-[#242936] bg-[#161920]/60 hover:bg-[#1A1D26] hover:border-purple-500/50 transition-all text-left shadow-lg relative overflow-hidden"
            >
              <div className="p-2 rounded-lg bg-purple-500/10 text-purple-400 border border-purple-500/30 mb-2.5 group-hover:scale-110 transition-transform">
                <Music className="w-4 h-4" />
              </div>
              <span className="text-xs font-bold text-white mb-0.5">M3U-Playliste (.m3u8)</span>
              <span className="text-[10px] text-gray-400 leading-relaxed">
                Universelle Playliste für DJ USB-Sticks, Mediaplayer & Player.
              </span>
              {downloadSuccess === 'm3u' && (
                <span className="absolute top-2 right-2 flex items-center gap-1 text-[9px] font-mono text-emerald-400 bg-emerald-950/80 px-2 py-0.5 rounded border border-emerald-500/40">
                  <Check className="w-3 h-3" /> Geladen
                </span>
              )}
            </button>

            {/* JSON Full Project Export */}
            <button
              onClick={handleExportJson}
              className="group flex flex-col items-start p-4 rounded-xl border border-[#242936] bg-[#161920]/60 hover:bg-[#1A1D26] hover:border-emerald-500/50 transition-all text-left shadow-lg relative overflow-hidden"
            >
              <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 mb-2.5 group-hover:scale-110 transition-transform">
                <Layers className="w-4 h-4" />
              </div>
              <span className="text-xs font-bold text-white mb-0.5">Set-Projekt (.json)</span>
              <span className="text-[10px] text-gray-400 leading-relaxed">
                Komplettes Set mit allen Hüllkurven, EQ-Kurven & Takt-Offsets.
              </span>
              {downloadSuccess === 'json' && (
                <span className="absolute top-2 right-2 flex items-center gap-1 text-[9px] font-mono text-emerald-400 bg-emerald-950/80 px-2 py-0.5 rounded border border-emerald-500/40">
                  <Check className="w-3 h-3" /> Geladen
                </span>
              )}
            </button>
          </div>

          {/* 3. RESTORE / IMPORT PROJECT */}
          {onImportProject && (
            <div className="pt-2 border-t border-[#242936] flex items-center justify-between">
              <span className="text-xs text-gray-400 font-mono">
                Ein vorher exportiertes Set-Projekt wiederherstellen:
              </span>
              <label className="flex items-center gap-1.5 px-3 py-1.5 bg-[#1E2330] hover:bg-[#2A3245] text-white rounded-lg text-xs font-mono font-bold cursor-pointer border border-[#242936] transition-colors">
                <Upload className="w-3.5 h-3.5 text-cyan-400" />
                <span>Projekt laden (.json)</span>
                <input
                  type="file"
                  accept=".json,.mulimaset.json"
                  onChange={handleFileImport}
                  className="hidden"
                />
              </label>
            </div>
          )}

        </div>

        {/* MODAL FOOTER */}
        <div className="p-4 border-t border-[#242936] bg-[#161920] flex items-center justify-end">
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-xl text-xs font-mono font-bold text-gray-400 hover:text-white hover:bg-[#242936] transition-colors"
          >
            Schließen
          </button>
        </div>

      </div>
    </div>
  );
}
